const actions = {
  DANHSACHDONTHUCANXULY_INIT: "DANHSACHDONTHUCANXULY_INIT",
  DANHSACHDONTHUCANXULY_INIT_SUCCESS: "DANHSACHDONTHUCANXULY_INIT_SUCCESS",
  DANHSACHDONTHUCANXULY_INIT_ERROR: "DANHSACHDONTHUCANXULY_INIT_ERROR",
  

  getData: (filterData) => ({
    type: actions.DANHSACHDONTHUCANXULY_INIT,
    payload: { filterData },
  }),
};

export default actions;
