const actions = {
    QUANLYTHAMSOHETHONG_GET_LIST_REQUEST: 'QUANLYTHAMSOHETHONG_GET_LIST_REQUEST',
    QUANLYTHAMSOHETHONG_GET_LIST_REQUEST_SUCCESS: 'QUANLYTHAMSOHETHONG_GET_LIST_REQUEST_SUCCESS',
    QUANLYTHAMSOHETHONG_GET_LIST_REQUEST_ERROR: 'QUANLYTHAMSOHETHONG_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.QUANLYTHAMSOHETHONG_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;
