const actions = {
    DANHMUCCHUCVU_GET_LIST_REQUEST: 'DANHMUCCHUCVU_GET_LIST_REQUEST',
    DANHMUCCHUCVU_GET_LIST_REQUEST_SUCCESS: 'DANHMUCCHUCVU_GET_LIST_REQUEST_SUCCESS',
    DANHMUCCHUCVU_GET_LIST_REQUEST_ERROR: 'DANHMUCCHUCVU_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.DANHMUCCHUCVU_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;
