const actions = {
  DANHMUCFILEDINHKEM_GET_LIST_REQUEST : 'DANHMUCFILEDINHKEM_GET_LIST_REQUEST',
  DANHMUCFILEDINHKEM_GET_LIST_REQUEST_SUCCESS : 'DANHMUCFILEDINHKEM_GET_LIST_REQUEST_SUCCESS',
  DANHMUCFILEDINHKEM_GET_LIST_REQUEST_ERROR : 'DANHMUCFILEDINHKEM_GET_LIST_REQUEST_ERROR',
  getList : (filterData) => (
    {
    type : actions.DANHMUCFILEDINHKEM_GET_LIST_REQUEST,
    payload : {filterData}
  })
}

export default actions