const actions = {
  GET_DATA_SOTIEPNHANGIANTIEP: "GET_DATA_SOTIEPNHANGIANTIEP",
  GET_DATA_SOTIEPNHANGIANTIEP_SUCCESS: "GET_DATA_SOTIEPNHANGIANTIEP_SUCCESS",
  GET_DATA_SOTIEPNHANGIANTIEP_ERROR: "GET_DATA_SOTIEPNHANGIANTIEP_ERROR",

  GET_DATA_DANHSACHLANHDAO: "GET_DATA_DANHSACHLANHDAO",
  GET_DATA_DANHSACHLANHDAO_SUCCESS: "GET_DATA_DANHSACHLANHDAO_SUCCESS",
  GET_DATA_DANHSACHLANHDAO_ERROR: "GET_DATA_DANHSACHLANHDAO_ERROR",

  getData: (filterData) => ({
    type: actions.GET_DATA_SOTIEPNHANGIANTIEP,
    payload: { filterData },
  }),
  getDataDanhSachLanhDao: (filterData) => ({
    type: actions.GET_DATA_DANHSACHLANHDAO,
    payload: { filterData },
  }),
};

export default actions;
