const actions = {
  GETDATATIEPDANTRUCTIEP_INIT: "GETDATATIEPDANTRUCTIEP_INIT",
  GETDATATIEPDANTRUCTIEP_INIT_SUCCESS: "GETDATATIEPDANTRUCTIEP_INIT_SUCCESS",
  GETDATATIEPDANTRUCTIEP_INIT_ERROR: "GETDATATIEPDANTRUCTIEP_INIT_ERROR",
  SETDONTHUTRUCTIEP: "SETDONTHUTRUCTIEP",
  SETDONTHUTRUCTIEP_SUCCESS: "SETDONTHUTRUCTIEP_SUCCESS",
  SETDONTHUTRUCTIEP_ERROR: "SETDONTHUTRUCTIEP_ERROR",
  LOAIDOITUONG_ID: "LOAIDOITUONG_ID",

  getData: (filterData) => ({
    type: actions.GETDATATIEPDANTRUCTIEP_INIT,
    payload: { filterData },
  }),
  setDonThuID: (DonThuID) => ({
    type: actions.SETDONTHUTRUCTIEP,
    payload: { DonThuID },
  }),
  setLoaiDoiTuongID: (ID) => ({
    type: actions.LOAIDOITUONG_ID,
    payload: { ID },
  }),
};

export default actions;
