const actions = {
  DANHSACHDONTHUHETHONG_INIT: "DANHSACHDONTHUHETHONG_INIT",
  DANHSACHDONTHUHETHONG_INIT_SUCCESS: "DANHSACHDONTHUHETHONG_INIT_SUCCESS",
  DANHSACHDONTHUHETHONG_INIT_ERROR: "DANHSACHDONTHUHETHONG_INIT_ERROR",
  

  getData: (filterData) => ({
    type: actions.DANHSACHDONTHUHETHONG_INIT,
    payload: { filterData },
  }),
};

export default actions;
