const actions = {
  DANHMUCFILE_GET_LIST_REQUEST : 'DANHMUCFILE_GET_LIST_REQUEST',
  DANHMUCFILE_GET_LIST_REQUEST_SUCCESS : 'DANHMUCFILE_GET_LIST_REQUEST_SUCCESS',
  DANHMUCFILE_GET_LIST_REQUEST_ERROR : 'DANHMUCFILE_GET_LIST_REQUEST_ERROR',
  DANHMUCCHUCNANGFILE_GET_LIST_REQUEST : 'DANHMUCCHUCNANGFILE_GET_LIST_REQUEST',
  DANHMUCCHUCNANGFILE_GET_LIST_REQUEST_SUCCESS : 'DANHMUCCHUCNANGFILE_GET_LIST_REQUEST_SUCCESS',
  DANHMUCCHUCNANGFILE_GET_LIST_REQUEST_ERROR : 'DANHMUCCHUCNANGFILE_GET_LIST_REQUEST_ERROR',
  getList : (filterData) => (
    {
    type : actions.DANHMUCFILE_GET_LIST_REQUEST,
    payload : {filterData}
  }),
  getListChucNang : (filterData) => (
    {
    type : actions.DANHMUCCHUCNANGFILE_GET_LIST_REQUEST,
    payload : {filterData}
  })
}

export default actions