const actions = {
    DANHMUCTHAMQUYEN_GET_LIST_REQUEST : 'DANHMUCTHAMQUYEN_GET_LIST_REQUEST',
    DANHMUCTHAMQUYEN_GET_LIST_REQUEST_SUCCESS : 'DANHMUCTHAMQUYEN_GET_LIST_REQUEST_SUCCESS',
    DANHMUCTHAMQUYEN_GET_LIST_REQUEST_ERROR : 'DANHMUCTHAMQUYEN_GET_LIST_REQUEST_ERROR',
    getList : (filterData) => (
      {
      type : actions.DANHMUCTHAMQUYEN_GET_LIST_REQUEST,
      payload : {filterData}
    })
  }
  
  export default actions