const actions = {
    DANHMUCBUOCXACMINH_GET_LIST_REQUEST : 'DANHMUCBUOCXACMINH_GET_LIST_REQUEST',
    DANHMUCBUOCXACMINH_GET_LIST_REQUEST_SUCCESS : 'DANHMUCBUOCXACMINH_GET_LIST_REQUEST_SUCCESS',
    DANHMUCBUOCXACMINH_GET_LIST_REQUEST_ERROR : 'DANHMUCBUOCXACMINH_GET_LIST_REQUEST_ERROR',
    getList : (filterData) => (
      {
      type : actions.DANHMUCBUOCXACMINH_GET_LIST_REQUEST,
      payload : {filterData}
    })
  }
  
  export default actions