const actions = {
    DANHMUCPHONGBAN_GET_LIST_REQUEST: 'DANHMUCPHONGBAN_GET_LIST_REQUEST',
    DANHMUCPHONGBAN_GET_LIST_REQUEST_SUCCESS: 'DANHMUCPHONGBAN_GET_LIST_REQUEST_SUCCESS',
    DANHMUCPHONGBAN_GET_LIST_REQUEST_ERROR: 'DANHMUCPHONGBAN_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.DANHMUCPHONGBAN_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;
