const actions = {
  GET_DATA_SOTIEPDAN: "GET_DATA_SOTIEPDAN",
  GET_DATA_SOTIEPDAN_SUCCESS: "GET_DATA_SOTIEPDAN_SUCCESS",
  GET_DATA_SOTIEPDAN_ERROR: "GET_DATA_SOTIEPDAN_ERROR",

  GET_DATA_DANKHONGDEN: "GET_DATA_DANKHONGDEN",
  GET_DATA_DANKHONGDEN_SUCCESS: "GET_DATA_DANKHONGDEN_SUCCESS",
  GET_DATA_DANKHONGDEN_ERROR: "GET_DATA_DANKHONGDEN_ERROR",

  GET_DATA_DANHSACHLANHDAO: "GET_DATA_DANHSACHLANHDAO",
  GET_DATA_DANHSACHLANHDAO_SUCCESS: "GET_DATA_DANHSACHLANHDAO_SUCCESS",
  GET_DATA_DANHSACHLANHDAO_ERROR: "GET_DATA_DANHSACHLANHDAO_ERROR",

  getData: (filterData) => ({
    type: actions.GET_DATA_SOTIEPDAN,
    payload: { filterData },
  }),

  getDataDanKhongDen: (filterData) => ({
    type: actions.GET_DATA_DANKHONGDEN,
    payload: { filterData },
  }),

  getDataDanhSachLanhDao: (filterData) => ({
    type: actions.GET_DATA_DANHSACHLANHDAO,
    payload: { filterData },
  }),
};

export default actions;
