const actions = {
    DANHMUCTRANGTHAIDON_GET_LIST_REQUEST: 'DANHMUCTRANGTHAIDON_GET_LIST_REQUEST',
    DANHMUCTRANGTHAIDON_GET_LIST_REQUEST_SUCCESS: 'DANHMUCTRANGTHAIDON_GET_LIST_REQUEST_SUCCESS',
    DANHMUCTRANGTHAIDON_GET_LIST_REQUEST_ERROR: 'DANHMUCTRANGTHAIDON_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.DANHMUCTRANGTHAIDON_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;