const actions = {
    DANHMUCPHANTICHKQ_GET_LIST_REQUEST: 'DANHMUCPHANTICHKQ_GET_LIST_REQUEST',
    DANHMUCPHANTICHKQ_GET_LIST_REQUEST_SUCCESS: 'DANHMUCPHANTICHKQ_GET_LIST_REQUEST_SUCCESS',
    DANHMUCPHANTICHKQ_GET_LIST_REQUEST_ERROR: 'DANHMUCPHANTICHKQ_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.DANHMUCPHANTICHKQ_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;
