const actions = {
  DANHSACHDONTHULOI_GET_LIST_REQUEST : 'DANHSACHDONTHULOI_GET_LIST_REQUEST',
  DANHSACHDONTHULOI_GET_LIST_REQUEST_SUCCESS : 'DANHSACHDONTHULOI_GET_LIST_REQUEST_SUCCESS',
  DANHSACHDONTHULOI_GET_LIST_REQUEST_ERROR : 'DANHSACHDONTHULOI_GET_LIST_REQUEST_ERROR',
  getList : (filterData) => (
    {
    type : actions.DANHSACHDONTHULOI_GET_LIST_REQUEST,
    payload : {filterData}
  })
}

export default actions