const actions = {
  DANHMUCNGUONDONDEN_GET_LIST_REQUEST : 'DANHMUCNGUONDONDEN_GET_LIST_REQUEST',
  DANHMUCNGUONDONDEN_GET_LIST_REQUEST_SUCCESS : 'DANHMUCNGUONDONDEN_GET_LIST_REQUEST_SUCCESS',
  DANHMUCNGUONDONDEN_GET_LIST_REQUEST_ERROR : 'DANHMUCNGUONDONDEN_GET_LIST_REQUEST_ERROR',
  getList : (filterData) => (
    {
    type : actions.DANHMUCNGUONDONDEN_GET_LIST_REQUEST,
    payload : {filterData}
  })
}

export default actions