const actions = {
  DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST:
    "DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST",
  DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST_SUCCESS:
    "DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST_SUCCESS",
  DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST_ERROR:
    "DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.DANHMUCHUONGGIAIQUYET_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
