const actions = {
    DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST: 'DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST',
    DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST_SUCCESS: 'DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST_SUCCESS',
    DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST_ERROR: 'DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST_ERROR',
    getList: (filterData) => ({
        type: actions.DANHMUCCHIATACHSAPNHAP_GET_LIST_REQUEST,
        payload: { filterData },
    }),
};

export default actions;
