const actions = {
  DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST:
    "DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST",
  DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST_SUCCESS:
    "DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST_SUCCESS",
  DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST_ERROR:
    "DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.DANHMUClOAIVANBANKEMTHEO_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
