const actions = {
  TONGHOPKETQUATTHANHCHINH_INIT_REQUEST: "TONGHOPKETQUATTHANHCHINH_INIT_REQUEST",
  TONGHOPKETQUATTHANHCHINH_INIT_REQUEST_SUCCESS: "TONGHOPKETQUATTHANHCHINH_INIT_REQUEST_SUCCESS",
  TONGHOPKETQUATTHANHCHINH_INIT_REQUEST_ERROR: "TONGHOPKETQUATTHANHCHINH_INIT_REQUEST_ERROR",

  getList: (filterData) => ({
    type: actions.TONGHOPKETQUATTHANHCHINH_INIT_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
